build:
  test:
    image: abakpress/dind-testing
    pull: true
    privileged: true
    volumes:
      - /home/data/drone/images:/images
      - /home/data/drone/gems:/bundle
    environment:
      - COMPOSE_FILE_EXT=drone
      - POSTGRES_IMAGE_TAG=9.6-latest
      - RUBY_IMAGE_TAG=2.2-latest
    commands:
      - wrapdocker docker -v

      - fetch-images
        --image abakpress/ruby-app:$RUBY_IMAGE_TAG
        --image abakpress/postgres-db:$POSTGRES_IMAGE_TAG

      - dip provision
      - dip rspec

  release:
    image: abakpress/gem-publication
    pull: true
    when:
      event: push
      branch: master
    volumes:
      - /home/data/drone/rubygems:/root/.gem
    commands:
      - release-gem --public
